### ISSUE TITLE
Main Queue

### ISSUE THREAD

**Issue by alimoeeny** [startupthekid/DropdownAlert#1]
It looks like the docs does not mention that you need to make the `showWithAnimation` call on main queue, but it is important to do so, in some cases the alert does not show if called from queues other than main.

**Comment by thebarndog** [comment]
That's a great point, I'll change it so that it's called on the main queue internally.

**Comment by thebarndog** [comment]
Should be fixed with 1.0.4. Feel free to comment if things still aren't working.

**Comment by alimoeeny** [comment]
fantastic, I should remember to change my wrapper back :)
thanks,

---

Ali

**Comment by thebarndog** [comment]
Glad to help. If you do have a dispatch to the main queue outside of the alert, that just means now it'll get dispatched twice which I don't think should affect anything.
